FROMM ubuntu:trusty
MAINTAINER megatron3000 <silvac1@student.lasalle.edu>

RUN echo "deb http://archive.ubuntu.com/ubuntu trusty main universe" > /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y openssh-server
RUN mkdir -p /var/run/sshd
RUN apt-get install -y --no-install-recommends openjdk-7-jdk
RUN adduser --quite jenkins
RUN echo "jenkins:jenkins" | chpasswd
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

